# Generated by Django 3.1.5 on 2021-02-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20210214_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='result_id',
            field=models.IntegerField(null=True),
        ),
    ]
