# Generated by Django 3.1.5 on 2021-02-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20210206_1417'),
        ('poll', '0004_delete_result'),
    ]

    operations = [
    ]
