# Generated by Django 3.1.5 on 2021-02-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20210215_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='answer_list',
            field=models.CharField(max_length=100),
        ),
    ]
