# Generated by Django 3.1.5 on 2021-02-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_auto_20210215_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Majorchart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_major', models.IntegerField(null=True)),
                ('result_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'majorchart',
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=800),
        ),
    ]
